### ISSUE TITLE
How to deploy BIg-IP in two different AZs for CFE

### ISSUE THREAD

**Issue by RavinderReddyF5** [F5Networks/terraform-aws-bigip-module#1]
How to deploy BIg-IP in two different AZs for CFE.
Can we deploy BIG-IP to two different AZs (us-east-1a and us-east-1f) with this Terraform Module?

this issue is referenced from: https://github.com/f5devcentral/terraform-aws-bigip-module/issues/64

**Comment by nmenant** [comment]
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#aws-cfe-prerequisites

CFE supports two BIG-IPs in two different AZ. The user should use the module to deploy one BIG-IP in each zones and then setup CFE accordingly

**Comment by trinaths** [comment]
@yamashin55 - Please share your findings with suggestions above.

**Comment by yamashin55** [comment]
thank  you for heip.
I understood CFE is supported multiple AZs. If we use this Terraform deploy to multiple AZs, Is there required run Terraform twice?

**Comment by JeffGiroux** [comment]
Different AZs require having 2 bigip modules calls. You can do this in one terraform job which calls the module twice (one for each bigip) with each pointing to different subnet IDs. One set in AZ1..one set in AZ2.

I have an example repo with examples using the modules. A snippet of code looks like below. 

example...
```
module "bigip" {
  source                     = "F5Networks/bigip-module/aws"
  mgmt_subnet_ids            = [{ "subnet_id" = var.mgmtSubnetAz1, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [var.mgmtNsg]
  external_subnet_ids        = [{ "subnet_id" = var.extSubnetAz1, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [var.extNsg]
  internal_subnet_ids        = [{ "subnet_id" = var.intSubnetAz1, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  internal_securitygroup_ids = [var.intNsg]
}

module "bigip2" {
  source                     = "F5Networks/bigip-module/aws"
  mgmt_subnet_ids            = [{ "subnet_id" = var.mgmtSubnetAz2, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [var.mgmtNsg]
  external_subnet_ids        = [{ "subnet_id" = var.extSubnetAz2, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [var.extNsg]
  internal_subnet_ids        = [{ "subnet_id" = var.intSubnetAz2, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  internal_securitygroup_ids = [var.intNsg]
}
```

**Comment by yamashin55** [comment]
Sorry for the delay in contacting you. I tried several methods, but my ability to run one time Terraform deploy including CFE tags was difficult.

I was able to solve the problem by running the Terraform deploy twice and then manually setting the CFE tag/role. Thank you very much. please close.
