### ISSUE TITLE
admin password expired after creation

### ISSUE THREAD

**Issue by harmonjeff** [F5Networks/terraform-aws-bigip-module#12]
Not sure what has changed to make this happen, but my deployments using terraform to create a BIG-IP instances in AWS suddenly have an admin password expired, making the rest of my DO and AS3 automation fail because the admin password is expired.

I have attempted to add some automation to change the admin password using PATCH commands to a few endpoints as suggested in https://community.f5.com/t5/technical-forum/rest-api-example-change-password/td-p/261858, but all of them give me an error message:

Authentication failed: Password expired. Update password via /mgmt/shared/authz/users

I have tried changing the admin password via automation using the /mgmt/shared/auth/users endpoint as well and it gives the same message.  I can't find a good way to change the admin password via automation.  Even certificate based ssh to the EC2 instance asks for the old and then new passwords.

I have been customizing the examples from this repo for a few months and had no issues with the admin password being expired when the automation completes until now.  The big thing I changed was the version of BIG-IP I am deploying. I updated to F5 BIGIP-16.1.2.2-0.0.28 PAYG-Good 25Mbps-220505071937-8e1217d4-a046-4cdf-894e-e38175bae37f thanks to recent authentication bypass CVEs.  

Is there something wrong with that image that has caused the admin password to be expired even though it is set via automation? Am I missing a step?

**Comment by RavinderReddyF5** [comment]
Created : INFRAANO-755 for tracking purpose
