### ISSUE TITLE
Feature: allow tagging of AWS interfaces and EIPs with custom tags

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-aws-bigip-module#22]
User would like to add unique tags per NIC and EIP. Currently, the var.tags is available but it is applied to all resources.

## Use Case
The use case would be for F5 Cloud Failover Extension to satisfy AWS requirements in which NICs and EIPs must be tagged with the failover labels, nic maps, and VIP IPs. Specifically the primary IP on the external NIC must be tagged with 2 tags for example. Then the public IPs must be tagged too.

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#define-aws-network-infrastructure-objects

## Current behavior
Successful deployment of BIG-IP, but all NICs are tagged the same. There is no way to specify unique tags per NIC. In order to setup HA failover, manual workaround needed to add tags after deployment to NICs and EIP is needed.

## Workaround
Must retrieve NIC info based on instance ID, then must do a tag resource. However, terraform recommends against using both tag resource and the resource itself due to overriding of each other. So...you must go enable the tag manually after. Still though, since the BIG-IP module doesn't contain those tags in state...upon next run...it will wipe out the values.

```
# BIG-IP 1 external NIC info
data "aws_network_interface" "bigip_ext" {
  filter {
    name   = "attachment.instance-id"
    values = [module.bigip.bigip_instance_ids]
  }
  filter {
    name   = "tag:Name"
    values = ["BIGIP-External-Public-Interface-0"]
  }
}
```

Then tag...
```
# Add Cloud Failover tags to BIG-IP 1 NICs
resource "aws_ec2_tag" "bigip_ext_label" {
  resource_id = data.aws_network_interface.bigip_ext.id
  key         = "f5_cloud_failover_label"
  value       = format("%s-%s", var.projectPrefix, random_id.buildSuffix.hex)
}
resource "aws_ec2_tag" "bigip_ext_nicmap" {
  resource_id = data.aws_network_interface.bigip_ext.id
  key         = "f5_cloud_failover_nic_map"
  value       = "external"
}
```

Retrieve EIP info...
```
# BIG-IP 1 Public VIP info
data "aws_eip" "bigip_vip" {
  public_ip = module.bigip.public_addresses["external_secondary_public"][0]
}
```

Tag EIP...
```
resource "aws_ec2_tag" "bigip_vip_label" {
  resource_id = data.aws_eip.bigip_vip.id
  key         = "f5_cloud_failover_label"
  value       = format("%s-%s", var.projectPrefix, random_id.buildSuffix.hex)
}
resource "aws_ec2_tag" "bigip_vip_ips" {
  resource_id = data.aws_eip.bigip_vip.id
  key         = "f5_cloud_failover_vips"
  value       = "${local.vm01_vip_ips.app1.ip},${local.vm02_vip_ips.app1.ip}"
}
```

## Suggestion
Add ability for the module parameters on the subnet lines to take additional tags.

Current...
```
module "bigip" {
  source                     = "F5Networks/bigip-module/aws"
  prefix                     = format("%s-3nic", var.projectPrefix)
  mgmt_subnet_ids            = [{ "subnet_id" = var.mgmtSubnetAz1, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [var.mgmtNsg]
  external_subnet_ids        = [{ "subnet_id" = var.extSubnetAz1, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [var.extNsg]
  internal_subnet_ids        = [{ "subnet_id" = var.intSubnetAz1, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  internal_securitygroup_ids = [var.intNsg]
}
```

With tags...
```
module "bigip" {
  source                     = "F5Networks/bigip-module/aws"
  prefix                     = format("%s-3nic", var.projectPrefix)
  mgmt_subnet_ids            = [{ "subnet_id" = var.mgmtSubnetAz1, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [var.mgmtNsg]
  external_subnet_ids        = [{ "subnet_id" = var.extSubnetAz1, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "", "more_tags_here" = "" }]
  external_securitygroup_ids = [var.extNsg]
  internal_subnet_ids        = [{ "subnet_id" = var.intSubnetAz1, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "", "more_tags_here" = "" }]
  internal_securitygroup_ids = [var.intNsg]
}
```

To be clear, the tagging should allow specific tagging of the NIC in addition to the EIP created by the module.

**Comment by JeffGiroux** [comment]
Similar feature needed in Azure repo too - https://github.com/F5Networks/terraform-azure-bigip-module/issues/33

**Comment by KrithikaChidambaram** [comment]
This request is now being tracked internally with ID INFRAANO-862. Thanks!
