### ISSUE TITLE
Update provider version to latest AWS 4.26.0

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-aws-bigip-module#23]
Current module provider pinned version is 3.8.0 or greater. Please update to use the latest 4.x version.

provider AWS v4.26.0 is current version as of 8/12 and it was published 5 days ago by AWS.

**Comment by RavinderReddyF5** [comment]
hi @JeffGiroux as it is pinned with greater than 3.8.0, hope we can upgrade to latest versions. do we have any issues for upgrade ?

**Comment by JeffGiroux** [comment]
I tested the module in my repo examples the other day and didn't see any issues with 4.26.0. And actually, the >=3.8.0 allows the 3.x and 4.x train. So actually, the 4.x version is allowed. Maybe for future purposes though to keep up with the resource provider updates, it would be wise to pin to 4.x train.

My versions...
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.26.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.8.0

My reference standalone example using this bigip module...
https://github.com/JeffGiroux/f5_terraform/tree/main/AWS/Standalone

**Comment by KrithikaChidambaram** [comment]
This request is now being tracked internally with ID INFRAANO-861. Thanks!

**Comment by RavinderReddyF5** [comment]
@JeffGiroux fixed in v1.1.7, please verify
