### ISSUE TITLE
Template_file not compatible with M1 and terraform versions

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-aws-bigip-module#31]
The template provider is causing terraform initialize errors for M1 users. The data template_file resource was to be used prior to terraform .11 and now .12 and on should use templatefile instead. Please update all the AWS BIG-IP code to remove data template_file resources and use local templatefile instead.

## error
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

**Comment by JeffGiroux** [comment]
identical https://github.com/F5Networks/terraform-azure-bigip-module/issues/38

**Comment by JeffGiroux** [comment]
bad block in...

examples/bigip_aws_1nic_deploy_custom_runtime_init/main.tf

data "template_file" "user_data_vm0" {
  mgmt_securitygroup_ids = [module.mgmt-network-security-group.security_group_id]
  custom_user_data       = data.template_file.user_data_vm0.rendered

**Comment by KrithikaChidambaram** [comment]
Hi Jeff, internal tracking ID for this request is: INFRAANO-923, thanks!

**Comment by RavinderReddyF5** [comment]
Hi @JeffGiroux, this issue addressed in v1.1.8, please open new issue if you see any problem
