### ISSUE TITLE
Unable to ssh to bigip using null resource launch site module

### ISSUE THREAD

**Issue by janibashamd** [F5Networks/terraform-aws-bigip-module#6]
Hi Team,

Using terraform terraform scripts i am able to deploy and configure bigip on public releases but when tried same on latest private builds scripts are failing to connect to ssh (_null resource launch site module_)

Working build AMI: _"F5 BIGIP-16.1.2.1-0.0.10 PAYG-Adv WAF Plus 200Mbps-211222202459" and "ami-04f64528e4ec2e338"_
Facing issue AMI: _"F5 BIGIP-tmos-bugs-staging-17.0.0-0.0.8316 PAYG-Adv WAF Plus 200Mbps-220312044158" and "[ami-07ea51ee96ce064ff] and others private builds._

**Error: timeout - last error: SSH authentication failed (admin@34.197.252.194:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain**

File links: 
1. User data: https://gitswarm.f5net.com/api-security/apisecurity/-/blob/main/tests/declarative-advanced-waf-policy/terraform/f5_onboard.tmpl
2. https://gitswarm.f5net.com/api-security/apisecurity/-/blob/main/tests/declarative-advanced-waf-policy/terraform/main.tf

If unable to access let me know i will give access permissions.

Terraform version used: "0.14.4"
f5networks/bigip versions: "1.8.0"

Let me know if any other things needed..

**Comment by KrithikaChidambaram** [comment]
Please reach out if you are facing the issue.

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!

**Comment by janibashamd** [comment]
@shshaik FYI..
