### ISSUE TITLE
Internal subnet interfaces don`t get assigned to BIG-IP Instance

### ISSUE THREAD

**Issue by kozbial** [F5Networks/terraform-aws-bigip-module#60]
Hi,

I have encountered a problem where after specifying multiple subnets in the "internal_subnet_ids" variable, interfaces are created in the EC2, but are not assigned to BIG-IP instances - only the first one gets assigned.

The problem might be that in the main.tf you always take the first element for private interfaces:
`  # set the private interface only if an interface is defined
  dynamic "network_interface" {
    for_each = length(aws_network_interface.private) > 0 ? [aws_network_interface.private[0].id] : toset([])
    content {
      network_interface_id = network_interface.value
      device_index         = (length(local.ext_interfaces) + 1) + index(tolist([aws_network_interface.private[0].id]), network_interface.value)
    }
  }`

**Comment by pgouband** [comment]
Hi @kozbial,

Can you share your Terraform files?

**Comment by RavinderReddyF5** [comment]
Hi @kozbial , please open new issue if issue still exist
